package com.studentTracer.servlets;


import javax.servlet.ServletException;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 * Servlet implementation class mail
 */
@WebServlet("/mail")
public class mail extends HttpServlet {
	
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public mail() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @throws Exception 
	 * @throws UnsupportedEncodingException 
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
    
    public void sendMail()  {
    	// Create a Properties object to contain connection configuration information.
    	 
    	      // Put recipient’s address
    	      String to = "marctsob2321@gmail.com";

    	      // Put sender’s address
    	      String from = "marctsob2321@gmail.com";
    	      final String username = "b465811bddb323";//username generated by Mailtrap
    	      final String password = "7e40875d63c869";//password generated by Mailtrap

    	      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
    	      String host = "smtp.gmail.com";
    	      String port="2525";

    	      Properties props = new Properties();
    	      props.put("mail.smtp.auth", "true");
    	      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
    	      props.put("mail.smtp.host", host);
    	      props.put("mail.smtp.port", port);// use one of the options in the SMTP settings tab in your Mailtrap Inbox

    	      // Get the Session object.
    	      Session session = Session.getInstance(props, new javax.mail.Authenticator() {
    	            protected PasswordAuthentication getPasswordAuthentication() {
    	               return new PasswordAuthentication(username, password);
    	    }
    	         });

    	      try {
    	    // Create a default MimeMessage object.
    	    Message message = new MimeMessage(session);
    	 
    	    // Set From: header field 
    	    message.setFrom(new InternetAddress(from));
    	 
    	    // Set To: header field
    	    message.setRecipients(Message.RecipientType.TO,
    	               InternetAddress.parse(to));
    	 
    	    // Set Subject: header field
    	    message.setSubject("My first message with JavaMail");
    	 
    	    // Put the content of your message
    	    message.setText("Hi there, this is my first message sent with JavaMail");

    	    // Send message
    	    Transport.send(message);

    	    System.out.println("Sent message successfully....");

    	      } catch (MessagingException e) {
     	         System.out.println("Erreur sebd: "+ e.getMessage());
    	         throw new RuntimeException(e);
    	      }
    	   }
    
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException{
		// TODO Auto-generated method stub
		this.sendMail();
		response.getWriter().append("Served at: ").append(request.getContextPath());

    }
	

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
